name: build and test simple node app
on:
  push:
    branches:
      - 'features'
    paths:
        '**.js'
permissions:
  issues: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    defaults:
      run:
        working-directory: ./node
    steps:
      - uses: actions/checkout@4.2.2
      - uses: actions/setup-node@v3.9.1
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install dependencies
        run: |
          npm install 
      - name: build and run the project
        run: node index.js &
      - name: test the app
        id: test
        run: echo "resulte=$(node test.js)" >> "$GITHUB_OUTPUT" 
      - if: ${{steps.test.outputs.resulte}} == "pass"
        run: |
          echo " APP TEST PASSSSS"
          echo ${{steps.test.outputs.resulte}}
           for i in `gh issue list | grep "Test Fail" | awk '{print $1 }' `; do  gh issue close $i ; done 
      - if:  ${{steps.test.outputs.resulte}} != "pass"
        run: gh issue create --title "Test Fail" --label "bug" --body "pleas adjust the file.json file.. to reurn Ahmad Khalaf"
